# Generated by Django 2.1.4 on 2018-12-28 08:20

from django.db import migrations, models
import django.db.models.deletion
import doll_sites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_chinese', models.CharField(max_length=60)),
                ('actress_name', models.CharField(blank=True, max_length=60, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.PROTECT, to='doll_sites.Company')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=doll_sites.models.upload_location)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doll_sites.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_link', models.CharField(max_length=200)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doll_sites.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_tag',
            field=models.ManyToManyField(blank=True, to='doll_sites.Tag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doll_sites.Series'),
        ),
    ]
