# Generated by Django 2.1.4 on 2019-03-05 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doll_sites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doll_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actress_name_ch', models.CharField(blank=True, max_length=60, null=True)),
                ('actress_name_jp', models.CharField(blank=True, max_length=60, null=True)),
                ('actress_name_en', models.CharField(blank=True, max_length=60, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=doll_sites.models.avatar_upload_location)),
                ('description', models.TextField(blank=True, max_length=9999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MemberConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default=None, max_length=100)),
                ('config_value', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1024)),
                ('order_id', models.CharField(max_length=1024)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('order_info', models.CharField(max_length=2048)),
                ('order_status', models.CharField(max_length=1024)),
                ('order_type', models.CharField(max_length=1024)),
                ('order_price', models.CharField(max_length=1024)),
                ('paid_price', models.CharField(blank=True, max_length=1024, null=True)),
                ('ppz_order_id', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_chinese', models.CharField(max_length=60)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('vip_photo', models.BooleanField(default=False)),
                ('buy_content', models.CharField(blank=True, max_length=60, null=True)),
                ('buy_price', models.IntegerField(blank=True, null=True)),
                ('buy_link', models.CharField(blank=True, max_length=360, null=True)),
                ('vip_bundle', models.BooleanField(default=False)),
                ('bundle_content', models.CharField(blank=True, max_length=60, null=True)),
                ('bundle_price', models.IntegerField(blank=True, null=True)),
                ('bundle_link', models.CharField(blank=True, max_length=360, null=True)),
                ('company', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.PROTECT, to='doll_sites.Company')),
                ('model_name', models.ManyToManyField(to='doll_sites.Actress')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=doll_sites.models.upload_location)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doll_sites.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_link', models.CharField(max_length=1024)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doll_sites.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default=None, max_length=100)),
                ('config_value', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAlbumPaidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1024)),
                ('order_id', models.CharField(max_length=1024)),
                ('photo_id', models.CharField(max_length=1024)),
                ('order_type', models.CharField(max_length=1024)),
                ('date_paid', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.BooleanField(default=False)),
                ('member_expire', models.DateField(blank=True, null=True)),
                ('count_coin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Album_paid_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_tag',
            field=models.ManyToManyField(blank=True, to='doll_sites.Tag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doll_sites.Series'),
        ),
    ]
