# Generated by Django 2.1.2 on 2018-12-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actress_name_ch', models.CharField(blank=True, max_length=60, null=True)),
                ('actress_name_jp', models.CharField(blank=True, max_length=60, null=True)),
                ('actress_name_en', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='actress_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doll_sites.Actress'),
        ),
    ]
