# Generated by Django 2.1.4 on 2019-03-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0002_auto_20190305_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberConfig123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default=None, max_length=100)),
                ('config_value', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
