# Generated by Django 2.1.2 on 2018-12-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0002_auto_20181229_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='actress_name',
        ),
        migrations.AddField(
            model_name='photo',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doll_sites.Actress'),
        ),
    ]
