# Generated by Django 2.1.4 on 2018-12-30 09:35

from django.db import migrations, models
import doll_sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0003_auto_20181229_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='actress_pic',
            field=models.ImageField(blank=True, null=True, upload_to=doll_sites.models.upload_location),
        ),
    ]
