# Generated by Django 2.1.4 on 2019-03-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0003_memberconfig123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberConfig123',
        ),
    ]
