# Generated by Django 2.1.4 on 2018-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0004_actress_actress_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
