# Generated by Django 2.1.4 on 2019-03-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0004_delete_memberconfig123'),
    ]

    operations = [
    ]
