# Generated by Django 2.1.3 on 2018-12-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0005_photo_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='vip_photo',
            field=models.BooleanField(default=False),
        ),
    ]
