# Generated by Django 2.1.4 on 2019-03-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0005_auto_20190305_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberconfig',
            name='config_value',
            field=models.CharField(default=None, max_length=9999),
        ),
    ]
