# Generated by Django 2.1.3 on 2018-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0007_photo_download_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='download_link',
            new_name='buy_link',
        ),
    ]
