# Generated by Django 2.1.4 on 2019-01-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0009_auto_20181231_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='bundle_link',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='vip_bundle',
            field=models.BooleanField(default=False),
        ),
    ]
