# Generated by Django 2.1.4 on 2019-01-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0010_auto_20190101_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='bundle_concent',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='bundle_price',
            field=models.IntegerField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='buy_concent',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='buy_price',
            field=models.IntegerField(blank=True, max_length=60, null=True),
        ),
    ]
