# Generated by Django 2.1.4 on 2019-01-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0011_auto_20190101_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actress',
            old_name='actress_pic',
            new_name='avatar',
        ),
    ]
