# Generated by Django 2.1.3 on 2019-01-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0012_auto_20190101_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='bundle_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
