# Generated by Django 2.1.4 on 2019-01-12 07:49

from django.db import migrations, models
import doll_sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0013_auto_20190101_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='description',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='actress',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=doll_sites.models.avatar_upload_location),
        ),
    ]
