# Generated by Django 2.1.4 on 2019-01-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0014_auto_20190112_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='description',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
    ]
