# Generated by Django 2.1.4 on 2019-01-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0014_auto_20190112_0800'),
        ('doll_sites', '0015_auto_20190112_1557'),
    ]

    operations = [
    ]
