# Generated by Django 2.1.2 on 2019-01-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0016_merge_20190112_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_links', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='photolink',
            name='pic_link',
            field=models.CharField(max_length=1024),
        ),
    ]
