# Generated by Django 2.1.2 on 2019-01-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0017_auto_20190117_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='payment_links',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='config_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
