# Generated by Django 2.1.2 on 2019-01-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0018_auto_20190117_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='config_value',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
