# Generated by Django 2.1.3 on 2019-01-29 19:12

from django.db import migrations, models
import doll_sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0019_siteconfig_config_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_pic', models.ImageField(upload_to=doll_sites.models.avatar_upload_location)),
                ('banner_title', models.CharField(max_length=999)),
                ('banner_link', models.CharField(max_length=999)),
            ],
        ),
    ]
