# Generated by Django 2.1.4 on 2019-01-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0020_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_price',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
