# Generated by Django 2.1.3 on 2019-02-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0022_auto_20190130_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
