# Generated by Django 2.1.4 on 2019-02-18 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('account', '0002_email_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doll_sites', '0022_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlbumPaidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1024)),
                ('order_id', models.CharField(max_length=1024)),
                ('photo_id', models.CharField(max_length=1024)),
                ('order_type', models.CharField(max_length=1024)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.EmailField(default=0, max_length=254)),
                ('member_type', models.IntegerField(default=0)),
                ('member_expire', models.DateTimeField(blank=True, null=True)),
                ('count_coin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Album_paid_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_ptr',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='bundle_concent',
            new_name='bundle_content',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='buy_concent',
            new_name='buy_content',
        ),
        migrations.AddField(
            model_name='order',
            name='ppz_order_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default='old', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photofile',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doll_sites.Photo'),
        ),
        migrations.AlterField(
            model_name='photolink',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doll_sites.Photo'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
