# Generated by Django 2.1.3 on 2019-02-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0023_photo_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
