# Generated by Django 2.1.3 on 2019-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0024_auto_20190208_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='history_views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
