# Generated by Django 2.1.3 on 2019-02-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0025_photo_history_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='hot_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actress',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
