# Generated by Django 2.1.3 on 2019-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_sites', '0027_actress_count_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='count_album',
            field=models.IntegerField(default=0),
        ),
    ]
